=== tduberne/matsim-playground/thibautd/src/main/resources/dtd/bikesharingfacilities_v1.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- $Id$ -->

<!-- ============================================================ -->

<!ELEMENT bikeSharingFacilities  (bikeSharingFacility*)>

<!ELEMENT bikeSharingFacility EMPTY>
<!ATTLIST bikeSharingFacility
          id                     CDATA #REQUIRED
          linkId                 CDATA #REQUIRED
          x                      CDATA #REQUIRED
          y                      CDATA #REQUIRED
          initialNumberOfBikes   CDATA #REQUIRED
          capacity               CDATA #REQUIRED>
<!-- ============================================================ -->

<!-- ROOT ELEMENT bikeSharingFacilities:
	 defines the location and characteristics of bike sharing stations.
	 They are called "facilities", because they are MATSim Facility objects
	 internally (a Facility is something with an Id, a Coordinate and a Link) -->

<!-- ============================================================ -->

<!-- ELEMENT bikeSharingFacility:
	 a single bike sharing station -->

<!-- ATTRIBUTE id:
	 a UNIQUE identifer for the facility.
	 format: string-->

<!-- ATTRIBUTE linkId:
	 the id of the link to which the facility should be associated
	 format: string-->

<!-- ATTRIBUTE x:
     x-coordinate of that facility.
     format: real number -->

<!-- ATTRIBUTE y:
     y-coordinate of that facility.
     format: real number -->

<!-- ATTRIBUTE capacity:
	 the maximum number of bikes the facility can hold.
	 format: unsigned integer -->

<!-- ATTRIBUTE initialNumberOfBikes:
	 initial number of bikes in the station.
	 must be lower than the capacity.
     format: unsigned integer -->

<!-- ============================================================ -->

=== tduberne/matsim-playground/thibautd/examples/bikesharing/hugegrid/bike-sharing-facilities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bikeSharingFacilities SYSTEM "bikesharingfacilities_v1.dtd">

<bikeSharingFacilities>
	<bikeSharingFacility id="bs--0-100---0-40" linkId="-0-100---0-40" x="39000.0" y="500.0" capacity="6" initialNumberOfBikes="3"/>
	<bikeSharingFacility id="bs--0-1007---0-1067" linkId="-0-1007---0-1067" x="46000.0" y="16500.0" capacity="8" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1008---0-1007" linkId="-0-1008---0-1007" x="46500.0" y="16000.0" capacity="7" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-1009---0-1008" linkId="-0-1009---0-1008" x="47500.0" y="16000.0" capacity="1" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1009---0-1010" linkId="-0-1009---0-1010" x="48500.0" y="16000.0" capacity="7" initialNumberOfBikes="6"/>
	<bikeSharingFacility id="bs--0-101---0-100" linkId="-0-101---0-100" x="39500.0" y="1000.0" capacity="6" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-101---0-161" linkId="-0-101---0-161" x="40000.0" y="1500.0" capacity="8" initialNumberOfBikes="5"/>
	<bikeSharingFacility id="bs--0-1011---0-1012" linkId="-0-1011---0-1012" x="50500.0" y="16000.0" capacity="1" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1012---0-1013" linkId="-0-1012---0-1013" x="51500.0" y="16000.0" capacity="6" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1012---0-952" linkId="-0-1012---0-952" x="51000.0" y="15500.0" capacity="3" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1015---0-1016" linkId="-0-1015---0-1016" x="54500.0" y="16000.0" capacity="6" initialNumberOfBikes="3"/>
	<bikeSharingFacility id="bs--0-1016---0-1017" linkId="-0-1016---0-1017" x="55500.0" y="16000.0" capacity="7" initialNumberOfBikes="6"/>
	<bikeSharingFacility id="bs--0-1023---0-1083" linkId="-0-1023---0-1083" x="2000.0" y="17500.0" capacity="5" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-1024---0-1025" linkId="-0-1024---0-1025" x="3500.0" y="17000.0" capacity="2" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1028---0-1027" linkId="-0-1028---0-1027" x="6500.0" y="17000.0" capacity="2" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1031---0-1030" linkId="-0-1031---0-1030" x="9500.0" y="17000.0" capacity="6" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-1033---0-1093" linkId="-0-1033---0-1093" x="12000.0" y="17500.0" capacity="8" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-1035---0-975" linkId="-0-1035---0-975" x="14000.0" y="16500.0" capacity="8" initialNumberOfBikes="6"/>
	<bikeSharingFacility id="bs--0-1041---0-1040" linkId="-0-1041---0-1040" x="19500.0" y="17000.0" capacity="7" initialNumberOfBikes="3"/>
	<bikeSharingFacility id="bs--0-1042---0-1043" linkId="-0-1042---0-1043" x="21500.0" y="17000.0" capacity="4" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1044---0-1043" linkId="-0-1044---0-1043" x="22500.0" y="17000.0" capacity="1" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1049---0-1050" linkId="-0-1049---0-1050" x="28500.0" y="17000.0" capacity="7" initialNumberOfBikes="5"/>
	<bikeSharingFacility id="bs--0-1049---0-1109" linkId="-0-1049---0-1109" x="28000.0" y="17500.0" capacity="2" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-105---0-104" linkId="-0-105---0-104" x="43500.0" y="1000.0" capacity="9" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-105---0-165" linkId="-0-105---0-165" x="44000.0" y="1500.0" capacity="5" initialNumberOfBikes="3"/>
	<bikeSharingFacility id="bs--0-1052---0-1053" linkId="-0-1052---0-1053" x="31500.0" y="17000.0" capacity="7" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1052---0-1112" linkId="-0-1052---0-1112" x="31000.0" y="17500.0" capacity="6" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1055---0-1054" linkId="-0-1055---0-1054" x="33500.0" y="17000.0" capacity="2" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-106---0-166" linkId="-0-106---0-166" x="45000.0" y="1500.0" capacity="6" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1062---0-1061" linkId="-0-1062---0-1061" x="40500.0" y="17000.0" capacity="2" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1066---0-1006" linkId="-0-1066---0-1006" x="45000.0" y="16500.0" capacity="5" initialNumberOfBikes="3"/>
	<bikeSharingFacility id="bs--0-1067---0-1127" linkId="-0-1067---0-1127" x="46000.0" y="17500.0" capacity="5" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1072---0-1071" linkId="-0-1072---0-1071" x="50500.0" y="17000.0" capacity="2" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1073---0-1013" linkId="-0-1073---0-1013" x="52000.0" y="16500.0" capacity="8" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1073---0-1133" linkId="-0-1073---0-1133" x="52000.0" y="17500.0" capacity="9" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1074---0-1073" linkId="-0-1074---0-1073" x="52500.0" y="17000.0" capacity="6" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1076---0-1136" linkId="-0-1076---0-1136" x="55000.0" y="17500.0" capacity="8" initialNumberOfBikes="6"/>
	<bikeSharingFacility id="bs--0-1077---0-1076" linkId="-0-1077---0-1076" x="55500.0" y="17000.0" capacity="6" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-1082---0-1081" linkId="-0-1082---0-1081" x="500.0" y="18000.0" capacity="1" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1083---0-1023" linkId="-0-1083---0-1023" x="2000.0" y="17500.0" capacity="4" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1085---0-1084" linkId="-0-1085---0-1084" x="3500.0" y="18000.0" capacity="4" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1088---0-1028" linkId="-0-1088---0-1028" x="7000.0" y="17500.0" capacity="6" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1089---0-1088" linkId="-0-1089---0-1088" x="7500.0" y="18000.0" capacity="9" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1091---0-1151" linkId="-0-1091---0-1151" x="10000.0" y="18500.0" capacity="4" initialNumberOfBikes="3"/>
	<bikeSharingFacility id="bs--0-1093---0-1092" linkId="-0-1093---0-1092" x="11500.0" y="18000.0" capacity="6" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1094---0-1095" linkId="-0-1094---0-1095" x="13500.0" y="18000.0" capacity="7" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1094---0-1154" linkId="-0-1094---0-1154" x="13000.0" y="18500.0" capacity="4" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1096---0-1156" linkId="-0-1096---0-1156" x="15000.0" y="18500.0" capacity="3" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-11---0-10" linkId="-0-11---0-10" x="9500.0" y="0.0" capacity="9" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1102---0-1101" linkId="-0-1102---0-1101" x="20500.0" y="18000.0" capacity="8" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-1104---0-1103" linkId="-0-1104---0-1103" x="22500.0" y="18000.0" capacity="1" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1109---0-1110" linkId="-0-1109---0-1110" x="28500.0" y="18000.0" capacity="0" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1110---0-1050" linkId="-0-1110---0-1050" x="29000.0" y="17500.0" capacity="7" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1119---0-1120" linkId="-0-1119---0-1120" x="38500.0" y="18000.0" capacity="0" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1122---0-1123" linkId="-0-1122---0-1123" x="41500.0" y="18000.0" capacity="7" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-1126---0-1127" linkId="-0-1126---0-1127" x="45500.0" y="18000.0" capacity="7" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-113---0-112" linkId="-0-113---0-112" x="51500.0" y="1000.0" capacity="1" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1130---0-1070" linkId="-0-1130---0-1070" x="49000.0" y="17500.0" capacity="3" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1132---0-1072" linkId="-0-1132---0-1072" x="51000.0" y="17500.0" capacity="3" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1132---0-1133" linkId="-0-1132---0-1133" x="51500.0" y="18000.0" capacity="7" initialNumberOfBikes="4"/>
	<bikeSharingFacility id="bs--0-1134---0-1135" linkId="-0-1134---0-1135" x="53500.0" y="18000.0" capacity="8" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1135---0-1195" linkId="-0-1135---0-1195" x="54000.0" y="18500.0" capacity="5" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1143---0-1144" linkId="-0-1143---0-1144" x="2500.0" y="19000.0" capacity="2" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1145---0-1144" linkId="-0-1145---0-1144" x="3500.0" y="19000.0" capacity="0" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1146---0-1086" linkId="-0-1146---0-1086" x="5000.0" y="18500.0" capacity="3" initialNumberOfBikes="1"/>
	<bikeSharingFacility id="bs--0-1150---0-1149" linkId="-0-1150---0-1149" x="8500.0" y="19000.0" capacity="7" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1151---0-1091" linkId="-0-1151---0-1091" x="10000.0" y="18500.0" capacity="9" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1152---0-1092" linkId="-0-1152---0-1092" x="11000.0" y="18500.0" capacity="2" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1153---0-1152" linkId="-0-1153---0-1152" x="11500.0" y="19000.0" capacity="9" initialNumberOfBikes="5"/>
	<bikeSharingFacility id="bs--0-1158---0-1098" linkId="-0-1158---0-1098" x="17000.0" y="18500.0" capacity="0" initialNumberOfBikes="0"/>
	<bikeSharingFacility id="bs--0-1162---0-1163" linkId="-0-1162---0-1163" x="21500.0" y="19000.0" capacity="3" initialNumberOfBikes="2"/>
	<bikeSharingFacility id="bs--0-1163---0-1223" linkId="-0-1163---0-1223" x="22000.0" y="19500.0" capacity="2" initialNumberOfBikes="1"/>
